### ISSUE TITLE
Kids should be able to access ChoreCenter without a parent code

### ISSUE THREAD

**Issue by luuuk** [yaretzj/ChoreCenter#73]
If I create a kid account before my parents create a parent account, I still would want to be able to access the ChoreCenter application to experiment with it's functionality. I would be happy to wait until later to configure my parent code...

**Comment by yaretzj** [comment]
We implemented the parent code block intentionally. Without a parent code we cannot link a parent and child which means the child would have no chores or rewards anyway. There is no functionality to experiment with without a parent.

**Comment by luuuk** [comment]
Gotcha, fair enough. I do think it would still hold value for parents to see what's inside the app before signing up. Maybe a feature preview would do the trick (obv stretch feature but could help out)

**Comment by luuuk** [comment]
Another use case for this is that if I'm developing on the kid UI, I def dont want to have to authenticate with a parent code every time I want to see changes. And I'm not sure how else I'd do this rn

**Comment by yaretzj** [comment]
Once two accounts are linked, you do not have to put in the parent code again on Signup, the code is just to link the accounts in the database backend

**Comment by yixiaoliuw** [comment]
Yes. As Jaden mentioned the parent code is not requested every time you log in to an account but solely when the kid account is created (this is to make sure there is at least one parent account whose chores and rewards are visible to the kid). We might introduce more exciting features in the future including kids can use parent codes to be linked with more than one parent account to access more chores and rewards options. The parent code is used for security because parents would not likely want some stranger to be able to invade their private interactions with kids. Last but not least, for development purpose, a Google account can be used to sign up for both a parent account and a kid account. For mock interactions a single account is sufficient.
